# Build-time input verification only. Installed libraries remain replaceable.
set(MEDIAFLOW_FFMPEG_BIN "${CMAKE_CURRENT_SOURCE_DIR}/third_party/ffmpeg/bin")
set(MEDIAFLOW_FFMPEG_RECORD "${CMAKE_CURRENT_SOURCE_DIR}/../third_party/ffmpeg")
file(READ "${MEDIAFLOW_FFMPEG_RECORD}/runtime-manifest.json" MEDIAFLOW_FFMPEG_MANIFEST)
string(JSON MEDIAFLOW_FFMPEG_COUNT LENGTH "${MEDIAFLOW_FFMPEG_MANIFEST}")
math(EXPR MEDIAFLOW_FFMPEG_LAST "${MEDIAFLOW_FFMPEG_COUNT}-1")
foreach(INDEX RANGE ${MEDIAFLOW_FFMPEG_LAST})
  string(JSON NAME GET "${MEDIAFLOW_FFMPEG_MANIFEST}" ${INDEX} name)
  string(JSON EXPECTED GET "${MEDIAFLOW_FFMPEG_MANIFEST}" ${INDEX} sha256)
  if(NOT EXISTS "${MEDIAFLOW_FFMPEG_BIN}/${NAME}")
    message(FATAL_ERROR "Prepare pinned FFmpeg with tools/processing/prepare_windows_ffmpeg.ps1 before building Windows.")
  endif()
  file(SHA256 "${MEDIAFLOW_FFMPEG_BIN}/${NAME}" ACTUAL)
  if(NOT ACTUAL STREQUAL EXPECTED)
    message(FATAL_ERROR "Unreviewed FFmpeg build input: ${NAME}")
  endif()
  install(FILES "${MEDIAFLOW_FFMPEG_BIN}/${NAME}" DESTINATION "${CMAKE_INSTALL_PREFIX}/processing/ffmpeg" COMPONENT Runtime)
endforeach()
install(DIRECTORY "${MEDIAFLOW_FFMPEG_RECORD}/" DESTINATION "${CMAKE_INSTALL_PREFIX}/licenses/ffmpeg" COMPONENT Runtime
  FILES_MATCHING PATTERN "*.txt" PATTERN "*.md" PATTERN "*.json" PATTERN "COPYING.LGPLv2.1")
